### ISSUE TITLE
Need to pass username and password with each backend request.

### ISSUE THREAD

**Issue by pygaurav** [ThePlenkov/express-sapui5#4]
Hi,

Could you please let us know how can we pass username and password with each backend request.

**Comment by ThePlenkov** [comment]
Hi Gaurav. I’m sorry - I haven’t supported it - I used basic auth in the browser. It must be very simple to adjust agent logic.

However I do really advise you to use another module ui5-fiori-sandbox . It’s very simple to use and supports same files
